/**
 * RCodeGenerator Module
 * 
 * Generates complete, executable R code for meta-analysis
 * based on data type and column mappings.
 */

import {
  DataType,
  AnalysisSuggestion,
  EffectMeasure,
  ColumnMapping,
  GeneratedCode,
  CodeSection
} from './types';
import { getEffectMeasureName } from './analysis-suggester';

/**
 * Generate complete R code for meta-analysis
 */
export function generateRCode(
  suggestion: AnalysisSuggestion,
  mapping: ColumnMapping,
  measure: EffectMeasure = suggestion.defaultMeasure
): GeneratedCode {
  switch (suggestion.dataType) {
    case DataType.BINARY:
      return generateBinaryCode(mapping, measure);
    
    case DataType.CONTINUOUS:
      return generateContinuousCode(mapping, measure);
    
    case DataType.PRECALCULATED:
      return generatePrecalculatedCode(mapping, measure);
    
    case DataType.DIAGNOSTIC:
      return generateDiagnosticCode(mapping);
    
    case DataType.CORRELATION:
      return generateCorrelationCode(mapping);
    
    case DataType.HAZARD_RATIO:
      return generateHazardRatioCode(mapping);
    
    default:
      return {
        script: '# Unable to generate code for unknown data type',
        sections: [],
        packages: []
      };
  }
}

function generateBinaryCode(
  mapping: ColumnMapping,
  measure: EffectMeasure
): GeneratedCode {
  const sections: CodeSection[] = [];
  
  const eventsT = mapping.events_treatment || 'events_treatment';
  const eventsC = mapping.events_control || 'events_control';
  const nT = mapping.n_treatment || 'n_treatment';
  const nC = mapping.n_control || 'n_control';
  const study = mapping.study || 'study';
  
  sections.push({
    title: 'Setup',
    description: 'Load required packages',
    code: `# ============================================
# Meta-Analysis of Binary Outcomes
# Generated by Glass Orchestrator
# ============================================

library(metafor)

# Load your data
# dat <- read.csv("your_data.csv")
`
  });
  
  sections.push({
    title: 'Calculate Effect Sizes',
    description: `Calculate ${measure} (${getEffectMeasureName(measure)}) and variance for each study`,
    code: `# ============================================
# Calculate Effect Sizes
# ============================================

# Calculate ${measure} (${getEffectMeasureName(measure)})
dat <- escalc(
  measure = "${measure}",
  ai = ${eventsT},
  bi = ${nT} - ${eventsT},
  ci = ${eventsC},
  di = ${nC} - ${eventsC},
  data = dat,
  slab = ${study}
)

# View calculated effect sizes
print(dat[, c("${study}", "yi", "vi")])
`
  });
  
  sections.push({
    title: 'Fit Random-Effects Model',
    description: 'Pool effect sizes using REML estimation',
    code: `# ============================================
# Fit Random-Effects Model
# ============================================

# Fit random-effects model
res <- rma(yi, vi, data = dat, method = "REML")

# Summary of results
summary(res)

# Pooled effect on original scale
predict(res, transf = exp, digits = 3)
`
  });
  
  sections.push({
    title: 'Forest Plot',
    description: 'Visualize individual and pooled effects',
    code: `# ============================================
# Forest Plot
# ============================================

# Forest plot
forest(res,
       atransf = exp,
       at = log(c(0.25, 0.5, 1, 2, 4)),
       xlim = c(-8, 6),
       header = TRUE,
       slab = dat$${study})

# Add prediction interval to forest plot
forest(res,
       atransf = exp,
       at = log(c(0.25, 0.5, 1, 2, 4)),
       xlim = c(-8, 6),
       header = TRUE,
       slab = dat$${study},
       addpred = TRUE)
`
  });
  
  sections.push({
    title: 'Heterogeneity Assessment',
    description: 'Assess between-study variability',
    code: `# ============================================
# Heterogeneity Assessment
# ============================================

cat("\\nHeterogeneity Assessment:\\n")
cat(sprintf("Q = %.2f, df = %d, p = %.4f\\n", res$QE, res$k - 1, res$QEp))
cat(sprintf("I² = %.1f%%\\n", res$I2))
cat(sprintf("τ² = %.4f (SE = %.4f)\\n", res$tau2, res$se.tau2))
cat(sprintf("τ = %.4f\\n", sqrt(res$tau2)))

# Prediction interval (95%)
pi <- predict(res, transf = exp)
cat(sprintf("\\n95%% Prediction Interval: %.2f to %.2f\\n", pi$pi.lb, pi$pi.ub))

# Interpretation
if (res$I2 < 25) {
  cat("\\nInterpretation: Low heterogeneity\\n")
} else if (res$I2 < 75) {
  cat("\\nInterpretation: Moderate heterogeneity\\n")
} else {
  cat("\\nInterpretation: High heterogeneity - consider subgroup analysis\\n")
}
`
  });
  
  sections.push({
    title: 'Publication Bias Assessment',
    description: "Funnel plot and Egger's test",
    code: `# ============================================
# Publication Bias Assessment
# ============================================

# Funnel plot
funnel(res, main = "Funnel Plot")

# Contour-enhanced funnel plot
funnel(res, level = c(90, 95, 99), shade = c("white", "gray55", "gray75"),
       refline = 0, legend = TRUE)

# Egger's regression test for funnel plot asymmetry
regtest(res)

# Rank correlation test (Begg's test)
ranktest(res)

# Trim-and-fill analysis
taf <- trimfill(res)
summary(taf)
cat(sprintf("\\nTrim-and-fill: %d studies imputed\\n", taf$k0))

# Funnel plot with imputed studies
funnel(taf, main = "Trim-and-Fill Funnel Plot")
`
  });
  
  sections.push({
    title: 'Sensitivity Analyses',
    description: 'Leave-one-out and influence diagnostics',
    code: `# ============================================
# Sensitivity Analyses
# ============================================

# Leave-one-out analysis
loo <- leave1out(res, transf = exp)
print(loo)

# Influence diagnostics
inf <- influence(res)
plot(inf)

# Baujat plot (contribution to heterogeneity vs influence)
baujat(res)
`
  });
  
  const script = sections.map(s => s.code).join('\n\n');
  
  return {
    script,
    sections,
    packages: ['metafor']
  };
}

function generateContinuousCode(
  mapping: ColumnMapping,
  measure: EffectMeasure
): GeneratedCode {
  const sections: CodeSection[] = [];
  
  const meanT = mapping.mean_treatment || 'mean_treatment';
  const meanC = mapping.mean_control || 'mean_control';
  const sdT = mapping.sd_treatment || 'sd_treatment';
  const sdC = mapping.sd_control || 'sd_control';
  const nT = mapping.n_treatment || 'n_treatment';
  const nC = mapping.n_control || 'n_control';
  const study = mapping.study || 'study';
  
  sections.push({
    title: 'Setup',
    description: 'Load required packages',
    code: `# ============================================
# Meta-Analysis of Continuous Outcomes
# Generated by Glass Orchestrator
# ============================================

library(metafor)

# Load your data
# dat <- read.csv("your_data.csv")
`
  });
  
  sections.push({
    title: 'Calculate Effect Sizes',
    description: `Calculate ${measure} (${getEffectMeasureName(measure)}) and variance`,
    code: `# ============================================
# Calculate Effect Sizes
# ============================================

# Calculate ${measure} (${getEffectMeasureName(measure)})
dat <- escalc(
  measure = "${measure}",
  m1i = ${meanT},
  sd1i = ${sdT},
  n1i = ${nT},
  m2i = ${meanC},
  sd2i = ${sdC},
  n2i = ${nC},
  data = dat,
  slab = ${study}
)

# View calculated effect sizes
print(dat[, c("${study}", "yi", "vi")])
`
  });
  
  sections.push({
    title: 'Fit Random-Effects Model',
    description: 'Pool effect sizes using REML estimation',
    code: `# ============================================
# Fit Random-Effects Model
# ============================================

# Fit random-effects model
res <- rma(yi, vi, data = dat, method = "REML")

# Summary of results
summary(res)

# Prediction interval
predict(res, digits = 3)
`
  });
  
  sections.push({
    title: 'Forest Plot',
    description: 'Visualize individual and pooled effects',
    code: `# ============================================
# Forest Plot
# ============================================

# Forest plot
forest(res,
       header = TRUE,
       slab = dat$${study},
       addpred = TRUE)
`
  });
  
  sections.push({
    title: 'Heterogeneity Assessment',
    description: 'Assess between-study variability',
    code: `# ============================================
# Heterogeneity Assessment
# ============================================

cat("\\nHeterogeneity Assessment:\\n")
cat(sprintf("Q = %.2f, df = %d, p = %.4f\\n", res$QE, res$k - 1, res$QEp))
cat(sprintf("I² = %.1f%%\\n", res$I2))
cat(sprintf("τ² = %.4f\\n", res$tau2))

# Prediction interval
pi <- predict(res)
cat(sprintf("\\n95%% Prediction Interval: %.2f to %.2f\\n", pi$pi.lb, pi$pi.ub))
`
  });
  
  sections.push({
    title: 'Publication Bias Assessment',
    description: "Funnel plot and Egger's test",
    code: `# ============================================
# Publication Bias Assessment
# ============================================

# Funnel plot
funnel(res, main = "Funnel Plot")

# Egger's regression test
regtest(res)

# Trim-and-fill analysis
taf <- trimfill(res)
summary(taf)
funnel(taf, main = "Trim-and-Fill Funnel Plot")
`
  });
  
  sections.push({
    title: 'Sensitivity Analyses',
    description: 'Leave-one-out and influence diagnostics',
    code: `# ============================================
# Sensitivity Analyses
# ============================================

# Leave-one-out analysis
loo <- leave1out(res)
print(loo)

# Influence diagnostics
inf <- influence(res)
plot(inf)
`
  });
  
  const script = sections.map(s => s.code).join('\n\n');
  
  return {
    script,
    sections,
    packages: ['metafor']
  };
}

function generateDiagnosticCode(mapping: ColumnMapping): GeneratedCode {
  const sections: CodeSection[] = [];
  
  const tp = mapping.tp || 'tp';
  const fp = mapping.fp || 'fp';
  const fn = mapping.fn || 'fn';
  const tn = mapping.tn || 'tn';
  const study = mapping.study || 'study';
  
  sections.push({
    title: 'Setup',
    description: 'Load required packages for diagnostic meta-analysis',
    code: `# ============================================
# Diagnostic Test Accuracy Meta-Analysis
# Generated by Glass Orchestrator
# ============================================

library(mada)
library(metafor)

# Load your data
# dat <- read.csv("your_data.csv")
`
  });
  
  sections.push({
    title: 'Prepare Data',
    description: 'Format 2x2 table data',
    code: `# ============================================
# Prepare Data
# ============================================

# Ensure data has correct column names for mada package
dat_mada <- data.frame(
  TP = dat$${tp},
  FP = dat$${fp},
  FN = dat$${fn},
  TN = dat$${tn}
)

# Calculate sensitivity and specificity for each study
dat_mada$sens <- dat_mada$TP / (dat_mada$TP + dat_mada$FN)
dat_mada$spec <- dat_mada$TN / (dat_mada$TN + dat_mada$FP)

print(dat_mada)
`
  });
  
  sections.push({
    title: 'Bivariate Model',
    description: 'Fit bivariate random-effects model',
    code: `# ============================================
# Bivariate Model (Reitsma et al.)
# ============================================

# Fit bivariate model
fit <- reitsma(dat_mada)
summary(fit)

# Summary operating point (pooled sensitivity and specificity)
cat("\\nSummary Operating Point:\\n")
cat(sprintf("Sensitivity: %.3f (95%% CI: %.3f - %.3f)\\n", 
            fit$coefficients[1,1], fit$coefficients[1,3], fit$coefficients[1,4]))
cat(sprintf("Specificity: %.3f (95%% CI: %.3f - %.3f)\\n",
            fit$coefficients[2,1], fit$coefficients[2,3], fit$coefficients[2,4]))

# Positive and negative likelihood ratios
sens <- fit$coefficients[1,1]
spec <- fit$coefficients[2,1]
lr_pos <- sens / (1 - spec)
lr_neg <- (1 - sens) / spec
cat(sprintf("\\nLR+: %.2f\\n", lr_pos))
cat(sprintf("LR-: %.2f\\n", lr_neg))
`
  });
  
  sections.push({
    title: 'SROC Curve',
    description: 'Summary ROC curve with confidence region',
    code: `# ============================================
# SROC Curve
# ============================================

# SROC curve with individual studies
plot(fit, 
     sroclwd = 2,
     main = "Summary ROC Curve")
points(1 - dat_mada$spec, dat_mada$sens, pch = 19)

# SROC curve with confidence and prediction regions
plot(fit, 
     sroclwd = 2,
     predict = TRUE,
     main = "SROC Curve with Prediction Region")
points(1 - dat_mada$spec, dat_mada$sens, pch = 19)
`
  });
  
  sections.push({
    title: 'Forest Plots',
    description: 'Paired forest plots for sensitivity and specificity',
    code: `# ============================================
# Forest Plots
# ============================================

# Forest plot - Sensitivity
forest(fit, type = "sens", main = "Sensitivity")

# Forest plot - Specificity
forest(fit, type = "spec", main = "Specificity")
`
  });
  
  sections.push({
    title: 'Heterogeneity',
    description: 'Assess heterogeneity in diagnostic accuracy',
    code: `# ============================================
# Heterogeneity Assessment
# ============================================

# Cochran's Q for sensitivity
sens_dat <- escalc(measure = "PLO", xi = dat_mada$TP, ni = dat_mada$TP + dat_mada$FN)
res_sens <- rma(yi, vi, data = sens_dat)
cat(sprintf("Sensitivity I²: %.1f%%\\n", res_sens$I2))

# Cochran's Q for specificity
spec_dat <- escalc(measure = "PLO", xi = dat_mada$TN, ni = dat_mada$TN + dat_mada$FP)
res_spec <- rma(yi, vi, data = spec_dat)
cat(sprintf("Specificity I²: %.1f%%\\n", res_spec$I2))
`
  });
  
  const script = sections.map(s => s.code).join('\n\n');
  
  return {
    script,
    sections,
    packages: ['mada', 'metafor']
  };
}

function generatePrecalculatedCode(
  mapping: ColumnMapping,
  measure: EffectMeasure
): GeneratedCode {
  const sections: CodeSection[] = [];
  
  const es = mapping.effect_size || 'effect_size';
  const se = mapping.se || 'se';
  const study = mapping.study || 'study';
  const needsTransform = ['OR', 'RR', 'HR'].includes(measure);
  
  sections.push({
    title: 'Setup',
    description: 'Load required packages',
    code: `# ============================================
# Meta-Analysis of Pre-calculated Effect Sizes
# Generated by Glass Orchestrator
# ============================================

library(metafor)

# Load your data
# dat <- read.csv("your_data.csv")
`
  });
  
  if (needsTransform) {
    sections.push({
      title: 'Transform Effect Sizes',
      description: `Transform ${measure} to log scale`,
      code: `# ============================================
# Transform Effect Sizes
# ============================================

# Transform to log scale for pooling
dat$yi <- log(dat$${es})
dat$sei <- dat$${se}

# For ratio measures, SE on log scale can be approximated from CI
# dat$sei <- (log(dat$ci_upper) - log(dat$ci_lower)) / (2 * 1.96)
`
    });
  }
  
  sections.push({
    title: 'Fit Random-Effects Model',
    description: 'Pool effect sizes using REML estimation',
    code: `# ============================================
# Fit Random-Effects Model
# ============================================

# Fit random-effects model
res <- rma(${needsTransform ? 'yi, sei = sei' : `yi = ${es}, sei = ${se}`}, 
           data = dat, 
           method = "REML",
           slab = ${study})

# Summary of results
summary(res)

# Pooled effect${needsTransform ? ' (back-transformed)' : ''}
predict(res${needsTransform ? ', transf = exp' : ''}, digits = 3)
`
  });
  
  sections.push({
    title: 'Forest Plot',
    description: 'Visualize individual and pooled effects',
    code: `# ============================================
# Forest Plot
# ============================================

# Forest plot
forest(res,
       ${needsTransform ? 'atransf = exp,' : ''}
       header = TRUE,
       slab = dat$${study},
       addpred = TRUE)
`
  });
  
  sections.push({
    title: 'Heterogeneity & Publication Bias',
    description: 'Assess heterogeneity and publication bias',
    code: `# ============================================
# Heterogeneity & Publication Bias
# ============================================

# Heterogeneity
cat(sprintf("I² = %.1f%%, τ² = %.4f\\n", res$I2, res$tau2))

# Funnel plot
funnel(res)

# Egger's test
regtest(res)

# Trim-and-fill
taf <- trimfill(res)
summary(taf)
`
  });
  
  const script = sections.map(s => s.code).join('\n\n');
  
  return {
    script,
    sections,
    packages: ['metafor']
  };
}

function generateCorrelationCode(mapping: ColumnMapping): GeneratedCode {
  const sections: CodeSection[] = [];
  
  const r = mapping.r || 'r';
  const n = mapping.n || 'n';
  const study = mapping.study || 'study';
  
  sections.push({
    title: 'Setup',
    description: 'Load required packages',
    code: `# ============================================
# Correlation Meta-Analysis
# Generated by Glass Orchestrator
# ============================================

library(metafor)

# Load your data
# dat <- read.csv("your_data.csv")
`
  });
  
  sections.push({
    title: 'Transform Correlations',
    description: "Apply Fisher's Z transformation",
    code: `# ============================================
# Transform Correlations
# ============================================

# Transform correlations to Fisher's Z
dat <- escalc(
  measure = "ZCOR",
  ri = ${r},
  ni = ${n},
  data = dat,
  slab = ${study}
)

# View transformed values
print(dat[, c("${study}", "${r}", "yi", "vi")])
`
  });
  
  sections.push({
    title: 'Fit Random-Effects Model',
    description: 'Pool correlations on Z scale',
    code: `# ============================================
# Fit Random-Effects Model
# ============================================

# Fit random-effects model
res <- rma(yi, vi, data = dat, method = "REML")

# Summary (on Z scale)
summary(res)

# Back-transform to correlation scale
predict(res, transf = transf.ztor, digits = 3)
`
  });
  
  sections.push({
    title: 'Forest Plot',
    description: 'Visualize correlations (back-transformed)',
    code: `# ============================================
# Forest Plot
# ============================================

# Forest plot (on correlation scale)
forest(res,
       atransf = transf.ztor,
       header = TRUE,
       slab = dat$${study},
       addpred = TRUE)
`
  });
  
  sections.push({
    title: 'Heterogeneity & Publication Bias',
    description: 'Assess heterogeneity and publication bias',
    code: `# ============================================
# Heterogeneity & Publication Bias
# ============================================

# Heterogeneity
cat(sprintf("I² = %.1f%%, τ² = %.4f\\n", res$I2, res$tau2))

# Funnel plot
funnel(res)

# Egger's test
regtest(res)
`
  });
  
  const script = sections.map(s => s.code).join('\n\n');
  
  return {
    script,
    sections,
    packages: ['metafor']
  };
}

function generateHazardRatioCode(mapping: ColumnMapping): GeneratedCode {
  const sections: CodeSection[] = [];
  
  const hr = mapping.hr || 'hr';
  const ciLower = mapping.ci_lower || 'ci_lower';
  const ciUpper = mapping.ci_upper || 'ci_upper';
  const study = mapping.study || 'study';
  
  sections.push({
    title: 'Setup',
    description: 'Load required packages',
    code: `# ============================================
# Hazard Ratio Meta-Analysis
# Generated by Glass Orchestrator
# ============================================

library(metafor)

# Load your data
# dat <- read.csv("your_data.csv")
`
  });
  
  sections.push({
    title: 'Transform Hazard Ratios',
    description: 'Convert HR and CI to log scale',
    code: `# ============================================
# Transform Hazard Ratios
# ============================================

# Transform to log scale
dat$yi <- log(dat$${hr})

# Calculate SE from confidence interval
dat$sei <- (log(dat$${ciUpper}) - log(dat$${ciLower})) / (2 * 1.96)

# View transformed values
print(dat[, c("${study}", "${hr}", "yi", "sei")])
`
  });
  
  sections.push({
    title: 'Fit Random-Effects Model',
    description: 'Pool hazard ratios on log scale',
    code: `# ============================================
# Fit Random-Effects Model
# ============================================

# Fit random-effects model
res <- rma(yi, sei = sei, data = dat, method = "REML", slab = ${study})

# Summary (on log scale)
summary(res)

# Back-transform to HR scale
predict(res, transf = exp, digits = 3)
`
  });
  
  sections.push({
    title: 'Forest Plot',
    description: 'Visualize hazard ratios with confidence intervals',
    code: `# ============================================
# Forest Plot
# ============================================

# Forest plot (on HR scale)
forest(res,
       atransf = exp,
       at = log(c(0.25, 0.5, 1, 2, 4)),
       header = TRUE,
       slab = dat$${study},
       addpred = TRUE)
`
  });
  
  sections.push({
    title: 'Heterogeneity & Publication Bias',
    description: 'Assess heterogeneity and publication bias',
    code: `# ============================================
# Heterogeneity & Publication Bias
# ============================================

# Heterogeneity
cat(sprintf("I² = %.1f%%, τ² = %.4f\\n", res$I2, res$tau2))

# Prediction interval
pi <- predict(res, transf = exp)
cat(sprintf("95%% Prediction Interval: %.2f to %.2f\\n", pi$pi.lb, pi$pi.ub))

# Funnel plot
funnel(res)

# Egger's test
regtest(res)
`
  });
  
  const script = sections.map(s => s.code).join('\n\n');
  
  return {
    script,
    sections,
    packages: ['metafor']
  };
}
