/**
 * PDF Report Generator Service
 * 
 * Generates PDF reports with forest plots and meta-analysis results.
 */

import { Platform, Share } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import type { MetaAnalysisResult, ForestPlotData, StudyResult } from '../webr';

export interface ReportOptions {
  title: string;
  author?: string;
  date?: string;
  language: 'pt' | 'en' | 'es';
  includeForestPlot: boolean;
  includeHeterogeneity: boolean;
  includeStudyTable: boolean;
  includeSummary: boolean;
  customNotes?: string;
}

export interface ReportData {
  analysis: MetaAnalysisResult;
  forestPlot?: ForestPlotData;
  spreadsheetName?: string;
}

// Translations
const TRANSLATIONS = {
  en: {
    title: 'Meta-Analysis Report',
    generatedBy: 'Generated by Meta Agent',
    summary: 'Summary',
    pooledEffect: 'Pooled Effect Size',
    confidenceInterval: 'Confidence Interval',
    model: 'Model',
    fixedEffect: 'Fixed Effect',
    randomEffects: 'Random Effects',
    heterogeneity: 'Heterogeneity Statistics',
    iSquared: 'I² (Inconsistency)',
    tauSquared: 'τ² (Between-study variance)',
    qStatistic: 'Q Statistic',
    qPvalue: 'Q p-value',
    studyTable: 'Individual Study Results',
    study: 'Study',
    effectSize: 'Effect Size',
    se: 'SE',
    ci: '95% CI',
    weight: 'Weight',
    forestPlot: 'Forest Plot',
    notes: 'Notes',
    interpretation: 'Interpretation',
    lowHeterogeneity: 'Low heterogeneity (I² < 25%)',
    moderateHeterogeneity: 'Moderate heterogeneity (25% ≤ I² < 75%)',
    highHeterogeneity: 'High heterogeneity (I² ≥ 75%)',
    significantEffect: 'The pooled effect is statistically significant (p < 0.05)',
    nonSignificantEffect: 'The pooled effect is not statistically significant (p ≥ 0.05)',
  },
  pt: {
    title: 'Relatório de Meta-Análise',
    generatedBy: 'Gerado por Meta Agent',
    summary: 'Resumo',
    pooledEffect: 'Tamanho de Efeito Combinado',
    confidenceInterval: 'Intervalo de Confiança',
    model: 'Modelo',
    fixedEffect: 'Efeito Fixo',
    randomEffects: 'Efeitos Aleatórios',
    heterogeneity: 'Estatísticas de Heterogeneidade',
    iSquared: 'I² (Inconsistência)',
    tauSquared: 'τ² (Variância entre estudos)',
    qStatistic: 'Estatística Q',
    qPvalue: 'Valor-p de Q',
    studyTable: 'Resultados dos Estudos Individuais',
    study: 'Estudo',
    effectSize: 'Tamanho de Efeito',
    se: 'EP',
    ci: 'IC 95%',
    weight: 'Peso',
    forestPlot: 'Forest Plot',
    notes: 'Notas',
    interpretation: 'Interpretação',
    lowHeterogeneity: 'Baixa heterogeneidade (I² < 25%)',
    moderateHeterogeneity: 'Heterogeneidade moderada (25% ≤ I² < 75%)',
    highHeterogeneity: 'Alta heterogeneidade (I² ≥ 75%)',
    significantEffect: 'O efeito combinado é estatisticamente significativo (p < 0,05)',
    nonSignificantEffect: 'O efeito combinado não é estatisticamente significativo (p ≥ 0,05)',
  },
  es: {
    title: 'Informe de Meta-Análisis',
    generatedBy: 'Generado por Meta Agent',
    summary: 'Resumen',
    pooledEffect: 'Tamaño del Efecto Combinado',
    confidenceInterval: 'Intervalo de Confianza',
    model: 'Modelo',
    fixedEffect: 'Efecto Fijo',
    randomEffects: 'Efectos Aleatorios',
    heterogeneity: 'Estadísticas de Heterogeneidad',
    iSquared: 'I² (Inconsistencia)',
    tauSquared: 'τ² (Varianza entre estudios)',
    qStatistic: 'Estadístico Q',
    qPvalue: 'Valor-p de Q',
    studyTable: 'Resultados de Estudios Individuales',
    study: 'Estudio',
    effectSize: 'Tamaño del Efecto',
    se: 'EE',
    ci: 'IC 95%',
    weight: 'Peso',
    forestPlot: 'Forest Plot',
    notes: 'Notas',
    interpretation: 'Interpretación',
    lowHeterogeneity: 'Baja heterogeneidad (I² < 25%)',
    moderateHeterogeneity: 'Heterogeneidad moderada (25% ≤ I² < 75%)',
    highHeterogeneity: 'Alta heterogeneidad (I² ≥ 75%)',
    significantEffect: 'El efecto combinado es estadísticamente significativo (p < 0,05)',
    nonSignificantEffect: 'El efecto combinado no es estadísticamente significativo (p ≥ 0,05)',
  },
};

class PDFGeneratorService {
  /**
   * Generate HTML content for the report
   */
  private generateHTML(data: ReportData, options: ReportOptions): string {
    const t = TRANSLATIONS[options.language];
    const { analysis } = data;
    const date = options.date || new Date().toLocaleDateString(
      options.language === 'pt' ? 'pt-BR' : options.language === 'es' ? 'es-ES' : 'en-US'
    );
    
    // Determine heterogeneity level
    let heterogeneityInterpretation = t.lowHeterogeneity;
    if (analysis.i_squared >= 75) {
      heterogeneityInterpretation = t.highHeterogeneity;
    } else if (analysis.i_squared >= 25) {
      heterogeneityInterpretation = t.moderateHeterogeneity;
    }
    
    // Determine significance
    const significanceInterpretation = analysis.p_value < 0.05
      ? t.significantEffect
      : t.nonSignificantEffect;
    
    let html = `
<!DOCTYPE html>
<html lang="${options.language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${options.title || t.title}</title>
  <style>
    @page {
      size: A4;
      margin: 2cm;
    }
    
    * {
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #1a1a1a;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    
    h1 {
      font-size: 24pt;
      color: #0a7ea4;
      border-bottom: 3px solid #0a7ea4;
      padding-bottom: 10px;
      margin-bottom: 5px;
    }
    
    h2 {
      font-size: 16pt;
      color: #333;
      margin-top: 30px;
      margin-bottom: 15px;
      border-bottom: 1px solid #ddd;
      padding-bottom: 5px;
    }
    
    .header-meta {
      color: #666;
      font-size: 10pt;
      margin-bottom: 30px;
    }
    
    .summary-box {
      background: linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%);
      border: 1px solid #0a7ea4;
      border-radius: 8px;
      padding: 20px;
      margin: 20px 0;
    }
    
    .summary-box h3 {
      margin-top: 0;
      color: #0a7ea4;
    }
    
    .stat-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin: 15px 0;
    }
    
    .stat-item {
      background: white;
      padding: 12px;
      border-radius: 6px;
      border: 1px solid #e0e0e0;
    }
    
    .stat-label {
      font-size: 9pt;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    
    .stat-value {
      font-size: 18pt;
      font-weight: bold;
      color: #0a7ea4;
    }
    
    .stat-detail {
      font-size: 9pt;
      color: #888;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
      font-size: 10pt;
    }
    
    th {
      background: #0a7ea4;
      color: white;
      padding: 10px 8px;
      text-align: left;
      font-weight: 600;
    }
    
    td {
      padding: 8px;
      border-bottom: 1px solid #e0e0e0;
    }
    
    tr:nth-child(even) {
      background: #f9f9f9;
    }
    
    tr:hover {
      background: #f0f9ff;
    }
    
    .forest-plot {
      background: white;
      border: 1px solid #ddd;
      border-radius: 8px;
      padding: 20px;
      margin: 20px 0;
      font-family: 'Courier New', monospace;
      font-size: 9pt;
      overflow-x: auto;
    }
    
    .forest-row {
      display: flex;
      align-items: center;
      margin: 4px 0;
      white-space: nowrap;
    }
    
    .forest-study {
      width: 150px;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    
    .forest-effect {
      width: 80px;
      text-align: right;
      padding-right: 10px;
    }
    
    .forest-ci {
      width: 120px;
      text-align: center;
    }
    
    .forest-plot-area {
      flex: 1;
      position: relative;
      height: 16px;
      background: #f5f5f5;
      border-left: 1px solid #999;
      border-right: 1px solid #999;
    }
    
    .forest-marker {
      position: absolute;
      top: 50%;
      transform: translateY(-50%);
      width: 8px;
      height: 8px;
      background: #0a7ea4;
      border-radius: 50%;
    }
    
    .forest-line {
      position: absolute;
      top: 50%;
      height: 2px;
      background: #0a7ea4;
      transform: translateY(-50%);
    }
    
    .forest-null-line {
      position: absolute;
      left: 50%;
      top: 0;
      bottom: 0;
      width: 1px;
      background: #999;
    }
    
    .forest-summary {
      background: #0a7ea4;
      color: white;
      padding: 8px;
      border-radius: 4px;
      margin-top: 10px;
    }
    
    .interpretation-box {
      background: #fff8e1;
      border-left: 4px solid #ffc107;
      padding: 15px;
      margin: 20px 0;
    }
    
    .notes-box {
      background: #f5f5f5;
      border-radius: 8px;
      padding: 15px;
      margin: 20px 0;
      font-size: 10pt;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      font-size: 9pt;
      color: #888;
      text-align: center;
    }
    
    .glass-logo {
      font-size: 14pt;
      margin-bottom: 5px;
    }
    
    @media print {
      body {
        padding: 0;
      }
      
      .summary-box, .interpretation-box, .notes-box {
        break-inside: avoid;
      }
      
      table {
        break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <h1>${options.title || t.title}</h1>
  <div class="header-meta">
    ${options.author ? `<strong>${options.author}</strong><br>` : ''}
    ${date}<br>
    <em>${t.generatedBy} 🦊</em>
  </div>
`;

    // Summary section
    if (options.includeSummary) {
      html += `
  <div class="summary-box">
    <h3>${t.summary}</h3>
    <div class="stat-grid">
      <div class="stat-item">
        <div class="stat-label">${t.pooledEffect}</div>
        <div class="stat-value">${analysis.estimate.toFixed(3)}</div>
        <div class="stat-detail">p = ${analysis.p_value < 0.001 ? '< 0.001' : analysis.p_value.toFixed(3)}</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">${t.confidenceInterval}</div>
        <div class="stat-value">[${analysis.ci_lower.toFixed(3)}, ${analysis.ci_upper.toFixed(3)}]</div>
        <div class="stat-detail">95% CI</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">${t.model}</div>
        <div class="stat-value">${analysis.model === 'FE' ? t.fixedEffect : t.randomEffects}</div>
        <div class="stat-detail">k = ${analysis.studies.length} ${options.language === 'pt' ? 'estudos' : options.language === 'es' ? 'estudios' : 'studies'}</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">${t.iSquared}</div>
        <div class="stat-value">${analysis.i_squared.toFixed(1)}%</div>
        <div class="stat-detail">τ² = ${analysis.tau_squared.toFixed(4)}</div>
      </div>
    </div>
  </div>
`;
    }

    // Heterogeneity section
    if (options.includeHeterogeneity) {
      html += `
  <h2>${t.heterogeneity}</h2>
  <table>
    <tr>
      <th>${t.iSquared}</th>
      <td>${analysis.i_squared.toFixed(2)}%</td>
    </tr>
    <tr>
      <th>${t.tauSquared}</th>
      <td>${analysis.tau_squared.toFixed(4)}</td>
    </tr>
    <tr>
      <th>${t.qStatistic}</th>
      <td>${analysis.q_statistic.toFixed(2)} (df = ${analysis.q_df})</td>
    </tr>
    <tr>
      <th>${t.qPvalue}</th>
      <td>${analysis.q_pvalue < 0.001 ? '< 0.001' : analysis.q_pvalue.toFixed(3)}</td>
    </tr>
  </table>
`;
    }

    // Forest plot section
    if (options.includeForestPlot && data.forestPlot) {
      html += `
  <h2>${t.forestPlot}</h2>
  <div class="forest-plot">
    ${this.generateASCIIForestPlot(data.forestPlot, options.language)}
  </div>
`;
    }

    // Study table section
    if (options.includeStudyTable) {
      html += `
  <h2>${t.studyTable}</h2>
  <table>
    <thead>
      <tr>
        <th>${t.study}</th>
        <th>${t.effectSize}</th>
        <th>${t.se}</th>
        <th>${t.ci}</th>
        <th>${t.weight}</th>
      </tr>
    </thead>
    <tbody>
      ${analysis.studies.map(study => `
      <tr>
        <td>${study.study}</td>
        <td>${study.yi.toFixed(3)}</td>
        <td>${study.sei.toFixed(3)}</td>
        <td>[${study.ci_lower.toFixed(3)}, ${study.ci_upper.toFixed(3)}]</td>
        <td>${(study.weight * 100).toFixed(1)}%</td>
      </tr>
      `).join('')}
    </tbody>
  </table>
`;
    }

    // Interpretation section
    html += `
  <h2>${t.interpretation}</h2>
  <div class="interpretation-box">
    <p><strong>${heterogeneityInterpretation}</strong></p>
    <p>${significanceInterpretation}</p>
  </div>
`;

    // Custom notes
    if (options.customNotes) {
      html += `
  <h2>${t.notes}</h2>
  <div class="notes-box">
    ${options.customNotes}
  </div>
`;
    }

    // Footer
    html += `
  <div class="footer">
    <div class="glass-logo">🦊 Glass - Meta Agent</div>
    <p>${t.generatedBy}</p>
  </div>
</body>
</html>
`;

    return html;
  }

  /**
   * Generate ASCII forest plot for HTML
   */
  private generateASCIIForestPlot(data: ForestPlotData, language: string): string {
    const { studies, summary } = data;
    
    // Find min and max for scaling
    const allValues = studies.flatMap(s => [s.ci_lower, s.ci_upper]);
    allValues.push(summary.ci_lower, summary.ci_upper);
    const min = Math.min(...allValues) - 0.5;
    const max = Math.max(...allValues) + 0.5;
    const range = max - min;
    const plotWidth = 40;
    
    const scaleToPlot = (value: number): number => {
      return Math.round(((value - min) / range) * plotWidth);
    };
    
    const nullLinePos = scaleToPlot(0);
    
    let plot = '';
    
    // Header
    const studyLabel = language === 'pt' ? 'Estudo' : language === 'es' ? 'Estudio' : 'Study';
    const effectLabel = language === 'pt' ? 'Efeito' : language === 'es' ? 'Efecto' : 'Effect';
    plot += `<div class="forest-row" style="font-weight: bold; border-bottom: 1px solid #999; padding-bottom: 5px; margin-bottom: 10px;">
      <span class="forest-study">${studyLabel}</span>
      <span class="forest-effect">${effectLabel}</span>
      <span class="forest-ci">95% CI</span>
      <span style="flex: 1; text-align: center;">Forest Plot</span>
    </div>`;
    
    // Studies
    studies.forEach(study => {
      const effectPos = scaleToPlot(study.yi);
      const ciLowerPos = scaleToPlot(study.ci_lower);
      const ciUpperPos = scaleToPlot(study.ci_upper);
      const lineWidth = ciUpperPos - ciLowerPos;
      
      plot += `<div class="forest-row">
        <span class="forest-study">${study.study}</span>
        <span class="forest-effect">${study.yi.toFixed(2)}</span>
        <span class="forest-ci">[${study.ci_lower.toFixed(2)}, ${study.ci_upper.toFixed(2)}]</span>
        <div class="forest-plot-area">
          <div class="forest-null-line" style="left: ${(nullLinePos / plotWidth) * 100}%;"></div>
          <div class="forest-line" style="left: ${(ciLowerPos / plotWidth) * 100}%; width: ${(lineWidth / plotWidth) * 100}%;"></div>
          <div class="forest-marker" style="left: calc(${(effectPos / plotWidth) * 100}% - 4px);"></div>
        </div>
      </div>`;
    });
    
    // Summary diamond
    const summaryPos = scaleToPlot(summary.estimate);
    const summaryLowerPos = scaleToPlot(summary.ci_lower);
    const summaryUpperPos = scaleToPlot(summary.ci_upper);
    
    const summaryLabel = language === 'pt' ? 'Resumo' : language === 'es' ? 'Resumen' : 'Summary';
    plot += `<div class="forest-summary">
      <strong>${summaryLabel}:</strong> ${summary.estimate.toFixed(3)} [${summary.ci_lower.toFixed(3)}, ${summary.ci_upper.toFixed(3)}]
    </div>`;
    
    return plot;
  }

  /**
   * Generate and save PDF report
   */
  async generateReport(
    data: ReportData,
    options: ReportOptions
  ): Promise<string> {
    const html = this.generateHTML(data, options);
    
    if (Platform.OS === 'web') {
      // On web, open print dialog
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        printWindow.print();
      }
      return 'print';
    }
    
    // On native, save HTML file and share
    const fileName = `meta-analysis-report-${Date.now()}.html`;
    const filePath = `${FileSystem.documentDirectory}${fileName}`;
    
    await FileSystem.writeAsStringAsync(filePath, html, {
      encoding: FileSystem.EncodingType.UTF8,
    });
    
    // Share the file
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(filePath, {
        mimeType: 'text/html',
        dialogTitle: options.title || 'Meta-Analysis Report',
      });
    }
    
    return filePath;
  }

  /**
   * Generate report preview HTML
   */
  generatePreview(data: ReportData, options: ReportOptions): string {
    return this.generateHTML(data, options);
  }
}

export const pdfGeneratorService = new PDFGeneratorService();

// Convenience exports
export const generateReport = (data: ReportData, options: ReportOptions) =>
  pdfGeneratorService.generateReport(data, options);
export const generateReportPreview = (data: ReportData, options: ReportOptions) =>
  pdfGeneratorService.generatePreview(data, options);
