/**
 * Knowledge Base Search Hook
 * 
 * Provides semantic search across the bundled knowledge base
 * using pre-generated embeddings for offline capability.
 */

import { useState, useCallback, useEffect } from 'react';
import { hybridRAG, loadBundledKnowledgeBase, type SearchResult } from '@/lib/rag';

// Import the bundled embeddings
// This will be loaded at runtime from the assets
let embeddingsLoaded = false;

export interface KnowledgeSearchResult {
  id: string;
  title: string;
  source: string;
  category: string;
  text: string;
  score: number;
  keywords?: string[];
}

export interface UseKnowledgeSearchReturn {
  search: (query: string) => Promise<KnowledgeSearchResult[]>;
  searchByCategory: (category: string) => KnowledgeSearchResult[];
  getCategories: () => string[];
  isLoading: boolean;
  isReady: boolean;
  error: string | null;
  stats: {
    totalChunks: number;
    categories: Record<string, number>;
  } | null;
}

/**
 * Load embeddings from bundled JSON file
 */
async function loadEmbeddings(): Promise<void> {
  if (embeddingsLoaded) return;
  
  try {
    // In React Native, we load from bundled assets
    // The embeddings.json is generated by scripts/generate-embeddings.ts
    const embeddingsData = require('@/assets/knowledge-base/embeddings.json');
    await hybridRAG.initializeLocal(embeddingsData);
    embeddingsLoaded = true;
  } catch (error) {
    console.warn('[Knowledge] Failed to load embeddings:', error);
    // Fall back to empty knowledge base
    await loadBundledKnowledgeBase();
    embeddingsLoaded = true;
  }
}

export function useKnowledgeSearch(): UseKnowledgeSearchReturn {
  const [isLoading, setIsLoading] = useState(false);
  const [isReady, setIsReady] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [stats, setStats] = useState<{ totalChunks: number; categories: Record<string, number> } | null>(null);

  // Initialize on mount
  useEffect(() => {
    let mounted = true;

    async function init() {
      try {
        await loadEmbeddings();
        if (mounted) {
          const ragStats = hybridRAG.getStats();
          if (ragStats.local) {
            setStats({
              totalChunks: ragStats.local.totalChunks,
              categories: ragStats.local.categories,
            });
          }
          setIsReady(true);
        }
      } catch (err) {
        if (mounted) {
          setError(err instanceof Error ? err.message : 'Failed to load knowledge base');
        }
      }
    }

    init();

    return () => {
      mounted = false;
    };
  }, []);

  const search = useCallback(async (query: string): Promise<KnowledgeSearchResult[]> => {
    if (!isReady) {
      return [];
    }

    setIsLoading(true);
    setError(null);

    try {
      const results = await hybridRAG.search(query, {
        topK: 10,
        minScore: 0.3,
      });

      return results.map((r: SearchResult) => ({
        id: r.chunk.id,
        title: r.chunk.metadata.title,
        source: r.chunk.metadata.source,
        category: r.chunk.metadata.category,
        text: r.chunk.text,
        score: r.score,
        keywords: r.chunk.metadata.keywords,
      }));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Search failed');
      return [];
    } finally {
      setIsLoading(false);
    }
  }, [isReady]);

  const searchByCategory = useCallback((category: string): KnowledgeSearchResult[] => {
    if (!isReady) {
      return [];
    }

    const ragStats = hybridRAG.getStats();
    if (!ragStats.local) {
      return [];
    }

    // Get all chunks from the category
    // This is a simplified version - in production you'd want pagination
    try {
      const results = hybridRAG.search('', {
        topK: 50,
        minScore: 0,
        categories: [category],
      });

      // Since search is async, we return empty and let the caller use the async version
      return [];
    } catch {
      return [];
    }
  }, [isReady]);

  const getCategories = useCallback((): string[] => {
    if (!stats) {
      return [];
    }
    return Object.keys(stats.categories);
  }, [stats]);

  return {
    search,
    searchByCategory,
    getCategories,
    isLoading,
    isReady,
    error,
    stats,
  };
}

/**
 * Format search results for terminal display
 */
export function formatKnowledgeResults(results: KnowledgeSearchResult[]): string {
  if (results.length === 0) {
    return `
No results found.

Try:
• Using different keywords
• Browsing by category with /knowledge
• Asking the AI directly about your topic
`.trim();
  }

  const lines: string[] = [
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `📚 Found ${results.length} result${results.length === 1 ? '' : 's'}`,
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '',
  ];

  for (const result of results.slice(0, 5)) {
    const relevance = Math.round(result.score * 100);
    const categoryIcon = getCategoryIcon(result.category);
    
    lines.push(`${categoryIcon} ${result.title}`);
    lines.push(`   Source: ${result.source}`);
    lines.push(`   Relevance: ${relevance}%`);
    lines.push('');
    
    // Truncate text to first 200 chars
    const preview = result.text.length > 200 
      ? result.text.slice(0, 200) + '...'
      : result.text;
    lines.push(`   ${preview}`);
    lines.push('');
    lines.push('───────────────────────────────────────────────────');
    lines.push('');
  }

  if (results.length > 5) {
    lines.push(`... and ${results.length - 5} more results`);
    lines.push('');
  }

  lines.push('💡 Tip: Ask the AI to explain any topic in more detail');

  return lines.join('\n');
}

function getCategoryIcon(category: string): string {
  switch (category) {
    case 'cochrane':
      return '📖';
    case 'seminal':
      return '📜';
    case 'r-docs':
      return '💻';
    case 'r-errors':
      return '🔧';
    case 'teaching':
      return '🎓';
    default:
      return '📄';
  }
}
